# Generated by Django 5.1.5 on 2025-01-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo', '0003_alter_comboimage_combo_alter_order_courier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='glovo.cartitem'),
        ),
    ]
